"""
Scene serialization for saving/loading scenes from the editor.
"""

import os
import json


class SceneSerializer:
    """
    Bridge between editor and file-based scene storage.

    Saves/loads scene files in Python format compatible with the engine.
    """

    def __init__(self):
        pass

    def save_scene(self, scene, file_path: str):
        """
        Save scene state to Python file.

        Args:
            scene: Scene instance to save
            file_path: Path to save the scene file
        """
        # Generate Python code for scene
        scene_code = self._generate_scene_code(scene)

        # Write to file
        with open(file_path, 'w') as f:
            f.write(scene_code)

        print(f"[SceneSerializer] Saved scene to: {file_path}")

    def _generate_scene_code(self, scene) -> str:
        """
        Generate Python code representation of scene.

        Args:
            scene: Scene instance

        Returns:
            Python code as string
        """
        lines = []

        # Header
        lines.append('"""')
        lines.append(f'Scene: {scene.__class__.__name__}')
        lines.append('Generated by Scribe Engine V2 Editor')
        lines.append('"""')
        lines.append('')

        # Imports
        lines.append('import pygame')
        lines.append('from v2_engine.core.scene import Scene')
        lines.append('from v2_engine.core.camera import Camera')
        lines.append('from v2_engine.utils.math import Vector2')
        lines.append('')

        # Collect sprite classes that need importing
        sprite_classes = set()
        if hasattr(scene, 'sprite_groups'):
            for group in scene.sprite_groups.values():
                for sprite in group.sprites:
                    sprite_classes.add(sprite.__class__.__name__)

        # Import sprite classes
        if sprite_classes:
            lines.append('# Sprite imports')
            for sprite_class in sorted(sprite_classes):
                # TODO: Determine proper import path dynamically
                lines.append(f'from v2_engine.sprites.sprite import {sprite_class}')
            lines.append('')

        # Class definition
        lines.append(f'class {scene.__class__.__name__}(Scene):')
        lines.append('    """Auto-generated scene."""')
        lines.append('')

        # __init__ method
        lines.append('    def __init__(self, game):')
        lines.append('        super().__init__(game)')
        lines.append('')

        # Collect all sprite group names
        group_names = []
        if hasattr(scene, 'sprite_groups'):
            group_names = list(scene.sprite_groups.keys())

        # Initialize sprite groups in __init__
        if group_names:
            lines.append('        # Initialize sprite groups')
            lines.append('        from v2_engine.sprites.group import SpriteGroup')
            for group_name in group_names:
                lines.append(f'        self.sprite_groups["{group_name}"] = SpriteGroup("{group_name}")')
            lines.append('')

        # on_enter method (where sprites are created)
        lines.append('    def on_enter(self):')
        lines.append('        """Called when scene becomes active."""')
        lines.append('        super().on_enter()')
        lines.append('')
        lines.append('        # Initialize camera')
        lines.append('        screen_width = self.game.screen.get_width()')
        lines.append('        screen_height = self.game.screen.get_height()')
        lines.append('        self.camera = Camera(screen_width, screen_height)')
        lines.append('')

        # Serialize sprites
        if hasattr(scene, 'sprite_groups'):
            for group_name, sprite_group in scene.sprite_groups.items():
                sprites = sprite_group.sprites
                if sprites:
                    lines.append(f'        # {group_name} group')

                    for i, sprite in enumerate(sprites):
                        sprite_var = f"{sprite.__class__.__name__.lower()}_{i}"
                        sprite_lines = self._serialize_sprite(sprite, sprite_var, group_name)
                        lines.extend(sprite_lines)
                        lines.append('')

        lines.append('')

        # Add render method
        lines.append('    def render(self, screen):')
        lines.append('        """Render all sprites with camera."""')
        lines.append('        # Clear screen')
        lines.append('        screen.fill((40, 40, 50))  # Dark gray background')
        lines.append('')
        lines.append('        # Render all sprite groups')
        if hasattr(scene, 'sprite_groups'):
            for group_name in scene.sprite_groups.keys():
                lines.append(f'        self.sprite_groups["{group_name}"].render(screen, self.camera)')
        lines.append('')

        return '\n'.join(lines)

    def _serialize_sprite(self, sprite, var_name: str, group_name: str) -> list:
        """
        Generate Python code for a sprite.

        Args:
            sprite: Sprite instance
            var_name: Variable name for the sprite
            group_name: Name of sprite group to add to

        Returns:
            List of code lines
        """
        lines = []

        # Create sprite instance
        class_name = sprite.__class__.__name__
        lines.append(f'        {var_name} = {class_name}()')

        # Set position
        lines.append(f'        {var_name}.position = Vector2({sprite.position.x}, {sprite.position.y})')

        # Set origin
        lines.append(f'        {var_name}.origin = Vector2({sprite.origin.x}, {sprite.origin.y})')

        # Set name if it exists
        if hasattr(sprite, 'name') and sprite.name:
            # Escape quotes in name string
            escaped_name = sprite.name.replace("'", "\\'")
            lines.append(f"        {var_name}.name = '{escaped_name}'")

        # Set image (create colored surface for now - TODO: handle actual image assets)
        if sprite.image:
            width = sprite.image.get_width()
            height = sprite.image.get_height()
            # Get the color from the center pixel
            try:
                color = sprite.image.get_at((width // 2, height // 2))
                lines.append(f'        {var_name}.image = pygame.Surface(({width}, {height}))')
                lines.append(f'        {var_name}.image.fill(({color.r}, {color.g}, {color.b}))')
            except:
                lines.append(f'        {var_name}.image = pygame.Surface(({width}, {height}))')
                lines.append(f'        {var_name}.image.fill((255, 255, 255))')

        # Set layer if it exists
        if hasattr(sprite, 'layer'):
            lines.append(f'        {var_name}.layer = {sprite.layer}')

        # Add to sprite group
        lines.append(f'        self.sprite_groups["{group_name}"].add({var_name})')

        return lines

    def save_scene_metadata(self, scene, metadata_path: str):
        """
        Save scene metadata as JSON.

        Args:
            scene: Scene instance
            metadata_path: Path to save metadata file
        """
        metadata = {
            'scene_name': scene.__class__.__name__,
            'sprite_count': self._count_sprites(scene),
            'sprite_groups': list(scene.sprite_groups.keys()) if hasattr(scene, 'sprite_groups') else []
        }

        with open(metadata_path, 'w') as f:
            json.dump(metadata, f, indent=2)

        print(f"[SceneSerializer] Saved metadata to: {metadata_path}")

    def _count_sprites(self, scene) -> int:
        """Count total sprites in scene."""
        count = 0
        if hasattr(scene, 'sprite_groups'):
            for group in scene.sprite_groups.values():
                count += len(group.sprites)
        return count
